// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleData.Core.Database;

#nullable disable

namespace VehicleData.Core.Database.Migrations
{
    [DbContext(typeof(VehicleContext))]
    [Migration("20260824074323_Trigger")]
    partial class Trigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleData.Core.Database.Model.TelemetryMessage", b =>
                {
                    b.Property<Guid>("TelemetryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasPrecision(4)
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasPrecision(4)
                        .HasColumnType("double precision");

                    b.Property<double>("Speed")
                        .HasPrecision(2)
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("TelemetryId");

                    b.HasIndex("VehicleId", "Timestamp");

                    b.ToTable("TelemetryMessage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
